export type EstiCRMType = {
  id: string;
  companyId: number;
  mainTypeId: number;
  investmentId: string;
  locationLatitude: number;
  locationLongitude: number;
  locationPostal: string;
  market: number;
  transaction: number;
  number: number;
  numberExport: number;
  price: number | string;
  priceCurrency: number;
  pricePermeter: number | string;
  areaTotal: number | string;
  areaUsable: string;
  areaPlot: string;
  availableDescription: string;
  availableDate: string;
  availableDateDays: string;
  addDate: string;
  activateDate: string;
  updateDate: string;
  exportDate: string;
  exchange: string;
  exchangeConditions: string;
  mdm: number;
  status: number;
  portalTitle: string;
  portalPromote: string;
  portalWwwTitle: string;
  typeName: string;
  locationCityForeign: string;
  locationStreetForeign: string;
  description: string;
  descriptionPrefix: string;
  descriptionSuffix: string;
  descriptionRoom: string;
  descriptionAdditional: string;
  tagList: string;
  videoLink: string;
  tourLink: string;
  brightKitchen: string | boolean;
  apartmentKitchen: string;
  apartmentFloor: number;
  apartmentRoomNumber: string;
  apartmentBathroomNumber: string | number;
  apartmentToiletNumber: string | number;
  apartmentRent: string | number;
  apartmentOwnership: string;
  apartmentFurnishings: string;
  apartmentHeight: string | number;
  commercialType: string;
  additionalLoggia: string | number;
  additionalBalcony: number;
  additionalTerrace: number;
  additionalBasement: number;
  additionalAttic: string | number;
  additionalStorage: string | number;
  additionalEntresol: string | number;
  additionalParking: string | number;
  additionalParkingunderground: string | number;
  additionalGarage: string | number;
  additionalGarden: string | number;
  securityIntercom: string | boolean;
  securityGuarded: string | boolean;
  securityReception: string | boolean;
  securityVideointercom: string | boolean;
  securityGated: string | boolean;
  securitySecuredoor: string | boolean;
  securityBlinds: string | boolean;
  securityGrating: string | boolean;
  securityVideocameras: string | boolean;
  securityMonitoring: string | boolean;
  securityAlarm: string | boolean;
  buildingElevatornumber: string | number;
  buildingElevatorhoist: string | boolean;
  buildingAdapted: string | boolean;
  buildingResidential: string;
  buildingFloornumber: string | number;
  buildingYear: string;
  buildingType: number;
  buildingSwimmingpool: string | boolean;
  buildingMaterial: string;
  buildingRoofmaterial: string;
  buildingHeating: string;
  buildingCondition: string;
  mediaPhone: string | boolean;
  mediaInternet: string | boolean;
  mediaTelevision: string | boolean;
  mediaGas: string | boolean;
  mediaWater: string | boolean;
  mediaCurrent: string | boolean;
  mediaSewerage: string | boolean;
  mediaCesspool: string | boolean;
  recreationForest: string | boolean;
  recreationPark: string | boolean;
  recreationLake: string | boolean;
  communicationPks: string | boolean;
  communicationBus: string | boolean;
  communicationSuburbanrailway: string | boolean;
  communicationSubway: string | boolean;
  communicationTram: string | boolean;
  communicationTrolleybus: string | boolean;
  communicationRailway: string | boolean;
  neighborhoodFitness: string | boolean;
  neighborhoodPool: string | boolean;
  neighborhoodBank: string | boolean;
  neighborhoodPharmacy: string | boolean;
  neighborhoodHospital: string | boolean;
  neighborhoodAirport: string | boolean;
  neighborhoodBazaar: string | boolean;
  neighborhoodShoppingcenter: string | boolean;
  neighborhoodNursery : string | boolean;
  neighborhoodKindergarten: string | boolean;
  neighborhoodPlayground: string | boolean;
  neighborhoodPrimaryschool: string | boolean;
  neighborhoodSecondaryschool: string | boolean;
  neighborhoodUniversity: string | boolean;
  neighborhoodGrocery: string | boolean;
  groundPlotwidth: string | number;
  groundPlotheight: string | number;
  groundType: string;
  groundFencing: string | boolean;
  groundRoad: string;
  groundOwnership: string;
  action: string;
  pictures: string[];
  companyName: string;
  agreementType: string;
  contactId: string;
  contactEmail: string;
  contactFirstname: string;
  contactLastname: string;
  contactPhone: string;
  locationCityName: string;
  locationStreetName: string;
  locationStreetType: string;
  locationPrecinctName: string;
  locationParentPrecinctName: string;
  locationCommuneName: string;
  locationDistrictName: string;
  locationProvinceName: string;
  locationPlaceName: string;
  locationCountryName: string;
  locationExportCityName: string;
  locationExportStreetName: string;
  locationExportStreetType: string;
  locationExportPrecinctName: string;
  locationExportCommuneName: string;
  locationExportDistrictName: string;
  locationExportProvinceName: string;
  locationExportPlaceName: string;
  locationExportCountryName: string;
  descriptionWebsite: string;
  apartmentLevelNumber: string | number;
  buildingCommecialStandard: string;
  locationBuildingnumber: string | number;
  locationApartmentnumber: string | number;
};
